### ISSUE TITLE
README.md links

### ISSUE THREAD

**Issue by WrathZA** [polarbearjs/polarbear#1]
Just a heads up. 12factor.net links are broken in your readme markdown.
I'm honestly not sure on the etiquette on whether I should have done a pull request or opened an issue for this... :)

**Comment by BenJanecke** [comment]
Howdy thanks for the heads up! :D 

For some reason I never got a email from gh for this issue :-1: 
I will endeavour to fix ASAP as Polarbear is under active development again starting today :tada:

**Comment by WrathZA** [comment]
Serious question. As a maintainer would you have preferred a PR or an issue?

**Comment by BenJanecke** [comment]
@WrathZA as with most things it depends, on something small I don't really mind doing it or merging a PR so it can go either way. Medium sized tasks is where PR's are really appreciated because it Is easy to go over them and check that they fit with our standards. When it comes to really big PR's I would personally prefer that they come from a Core Member. 

Does that help?
